# Generated by Django 4.2.20 on 2025-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='author', to='books_authors_app.authors'),
        ),
    ]
