# Generated by Django 4.2.20 on 2025-04-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_books_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books_authors_app.authors'),
        ),
    ]
